[build]
  functions = "netlify/functions/"

# Imposta il timeout specificamente per la funzione 'gemini'
[functions.gemini]
  timeout = 26

[[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200
